name: hares

volumes:
  hares_data:

services:
  hares-app:
    ports:
      - 127.0.0.1:9000:80
    build: .
  couchdb:
    image: couchdb
    ports:
      - 127.0.0.1:5984:5984
    volumes:
      - hares_data:/opt/couchdb/data
      - ./local.ini:/opt/couchdb/etc/local.d/local.ini
