name: hares

volumes:
  hares_data:

services:
  couchdb:
    image: couchdb
    ports:
      - 127.0.0.1:5984:5984
    volumes:
      - hares_data:/opt/couchdb/data
      - ./local.ini:/opt/couchdb/etc/local.d/local.ini
